'use strict';
const gulp = require('gulp');
const concat = require('gulp-concat');
const uglify = require('gulp-uglify');
const rename = require('gulp-rename');
gulp.task('example', () => {
  return gulp.src('scripts/*.js')   // all JavaScript files ...
    .pipe(concat('all.js'))         // ... concatenate ...
    .pipe(gulp.dest('dist'))        // ... copy to a destination folder ...
    .pipe(rename('all.min.js'))     // ... rename file ...
    .pipe(uglify())                 // ... minify ...
    .pipe(gulp.dest('dist'));       // ... and copy the minified file
});

gulp.task('default', ['example']);
