'use strict';
const selectElement = document.getElementById('grade');  // the pick list
const options = [                                        // a list of values
  'A (90%-100%)', 
  'B (80%-89%)', 
  'C (70%-79%)', 
  'D (60%-69%)', 
  'F (0%-59%)', 
   
];
for(let i=0; i<options.length; i++) {                     // For every value in ...
                                                          // ... the list ...
  const optionElement = document.createElement('option'); // ... create one ...
                                                          // ... selection element, ...
  const optionText = document.createTextNode(options[i]); // ... create the ...
                                                          // ... corresponding text, ...
  optionElement.appendChild(optionText);                  // ... append the Text to ...
                                                          // ... the element.
  selectElement.appendChild(optionElement);               // and append the element 
                                                          // to the pick list.
}
