'use strict';
document.addEventListener('DOMContentLoaded', () => {
  const sourceList = document.getElementById('source');  // the source list
  const targetList = document.getElementById('target');  // the target list
  const copyButton = document.getElementById('move');    // the Move ...
                                                         // ... button
  copyButton.addEventListener('click', function() {      // When clicking the ...
                                                         // ... button:
    while(sourceList.hasChildNodes()) {                  // While there are items ...
                                                         // ... in the source list, ...
      const item = sourceList.removeChild(               // ... the first item is ...
        sourceList.firstChild);                          // ... removed from this list ...
      targetList.appendChild(item);                      // ... and added to the ...
                                                         // ... target list.
    }
  });  
});