'use strict';
let result = 5;
result += 11;  // the variable now has a value of 16 ...
result -= 1;   // ... now a value of 15 ...
result /= 3;   // ... now a value of 5 ...
result *= 4;   // ... now a value of 20 ...
result %= 5;   // ... and now a value of 0.
